//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsPortalDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleo
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public int categoria { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public int published_by { get; set; }
    
        public virtual categoria categoria1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
